### PR TITLE
Parameter to set label length in ZPL

### PR DESCRIPTION
**Pull request by neilsb**
Added parameter `setLabelLength` which, when true, will include the ZPL command `^LLxxxx` to set the label length to the size of print content in the returned ZPL.

When using continuous feed and printing a small PDF, the printer will still spool out the full length of the label size.  While the Label Length can be set independently, if you are printing pdfs of different length you would need to work out the length of each label and set it prior to printing the page.   This PR allows the returned ZPL content to include the label length for each page, which is the image height.

### CODE REVIEW

**Comment by sungaila** [comment]
Setting `setLabelLength` to `true` by default would be a breaking change, right? The ZPL II Programming Guide says:

> Once you have issued `^LL`, the setting is retained until you turn off the printer or send a new `^LL` command.

Other than that I am fine with including your addition. :-) Please modify the [PublicAPI text files](https://github.com/neilsb/PDFtoZPL/tree/set-label-length/PDFtoZPL/PublicAPI) with the new method signatures (I use them for tracking breaking changes via compiler warnings).

I'll add some unit tests later on, fix the SonarCloud pipeline and publish a new release.

**Review by sungaila — APPROVED** [review]

**Comment by neilsb** [comment]
> Setting `setLabelLength` to `true` by default would be a breaking change, right?

Yes.  This setting is only likely to be useful for people using continuous labels (or receipt paper).  I suspect that pre-cut labels on roll is a more common scenario, and in this case you would not want the label length to be set to the PDF side, but would always want the printer to feed an entire label through for each page.

I'll get the API Text files updated shortly.

**Comment by neilsb** [comment]
I've updated the public API text files. Still getting a pile of warnings though, so let me know if I've done it incorrectly.

I can look at adding a PDF with pages of differing length to the test project, and a couple of tests if you'd like?

**Comment by sungaila** [comment]
> Still getting a pile of warnings though, so let me know if I've done it incorrectly.

The Android/Xamarin builds are broken right now but that is not the fault of this PR.

> I can look at adding a PDF with pages of differing length to the test project, and a couple of tests if you'd like?

Thanks, but I'll stick with both test assets `SocialPreview.pdf` and `Wikimedia_Commons_web.pdf` for now. The tests will be rather simple and check interactions between some optional parameters.

**Review by sungaila — APPROVED** [review]

**Comment by sungaila** [comment]
@neilsb [PDFtoZPL 3.4.0](https://www.nuget.org/packages/PDFtoZPL/3.4.0) just went live, thanks for your contribution! :-)

> It may be useful to some to have an "margin" value, to allow setting the label length to the page content +20 (for example) to create a break between pages.

I've been thinking about this and decided it is too niche to justify an optional parameter (that is entirely dependant on `setLabelLength`). As a quick and dirty workaround this code would be sufficient:

```csharp
public static string ConvertPdfPageWithMargin(Stream pdfStream, int margin)
{
	var result = PDFtoZPL.Conversion.ConvertPdfPage(pdfStream, setLabelLength: true);

	int llEnd = result.IndexOf("^LL") + "^LL".Length;
	int gfStart = result.IndexOf("^GFA");
	string llSubtring = result.Substring(llEnd, gfStart - llEnd);
	int labelLength = int.Parse(llSubtring);

	return result.Replace(llSubtring, $"^LL{labelLength + margin}");
}
```

**Pull request merged**
